// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWebApp.Models;

#nullable disable

namespace TodoWebApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20220419223101_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoWebApp.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCategoria"), 1L, 1);

                    b.Property<string>("Colore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCategoria");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("TodoWebApp.Models.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Completata")
                        .HasColumnType("bit");

                    b.Property<string>("Dettagli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IDUtente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Promemoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDUtente");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("TodoWebApp.Models.Utente", b =>
                {
                    b.Property<int>("IDUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUtente"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtente");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("TodoWebApp.Models.Todo", b =>
                {
                    b.HasOne("TodoWebApp.Models.Categoria", "Categoria")
                        .WithMany("Todos")
                        .HasForeignKey("IDCategoria");

                    b.HasOne("TodoWebApp.Models.Utente", "Utente")
                        .WithMany("Todos")
                        .HasForeignKey("IDUtente");

                    b.Navigation("Categoria");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("TodoWebApp.Models.Categoria", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("TodoWebApp.Models.Utente", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
